FROM ubuntu:18.04

RUN apt-get update -y 

#RUN apt-get upgrade -y 

RUN apt-get install python3-dev -y 

RUN apt-get install python3-pip -y 

RUN apt-get install git -y

RUN apt-get install ffmpeg -y

RUN python3 -m pip install --upgrade pip 

RUN python3 -m pip install urllib3==1.26.10

#RUN python3 -m pip install --upgrade MarkupSafe==2.1.2

#RUN python3 -m pip install flask 

RUN python3 -m pip install opencv-python 

RUN git clone https://github.com/mvimplis2013/machine-learning-python.git

WORKDIR machine-learning-python

#ENTRYPOINT python3 setup-video.py install 